const cfg=window.SITE_CONFIG||{};
const configured=cfg.supabaseUrl && !cfg.supabaseUrl.includes('YOUR_') && cfg.supabaseAnonKey && !cfg.supabaseAnonKey.includes('YOUR_');
const $=id=>document.getElementById(id);
let supabase=null,currentNews=[];
function status(el,msg,type=''){el.textContent=msg;el.className='status '+type}
function ownerAllowed(email){return (cfg.ownerEmails||[]).map(x=>x.toLowerCase()).includes((email||'').toLowerCase())}
function clearForm(){['newsId','newsTitle','newsDate','newsExcerpt','newsBody'].forEach(id=>$(id).value='');$('newsImages').value='';$('selectedFiles').innerHTML='';$('newsFormTitle').textContent='افزودن خبر'}
async function init(){
 if(!configured){status($('loginStatus'),'ابتدا config.js را با URL و Anon Key پروژه Supabase تنظیم کن.','error');return}
 supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
 const {data:{session}}=await supabase.auth.getSession(); if(session) await afterLogin(session); else status($('loginStatus'),'ایمیل مجاز را وارد کن و لینک ورود را دریافت کن.');
 supabase.auth.onAuthStateChange(async(_event,session)=>{if(session) await afterLogin(session); else showLogin()});
}
async function afterLogin(session){
 const email=session.user.email||'';
 if(!ownerAllowed(email)){await supabase.auth.signOut();status($('loginStatus'),'این ایمیل در فهرست مالک نیست.','error');return}
 const {data,error}=await supabase.from('owner_access').select('email,enabled').eq('email',email.toLowerCase()).maybeSingle();
 if(error||!data||!data.enabled){await supabase.auth.signOut();status($('loginStatus'),'دسترسی این ایمیل در پایگاه داده مجاز نیست.','error');return}
 $('loginCard').classList.add('hidden');$('panel').classList.remove('hidden');$('who').textContent='وارد شده: '+email;await loadContent();await loadNews();
}
function showLogin(){$('panel').classList.add('hidden');$('loginCard').classList.remove('hidden')}
async function loadContent(){for(const slug of ['ashayer','cooperative']){const {data}=await supabase.from('site_content').select('*').eq('slug',slug).single();if(!data)continue;if(slug==='ashayer'){ $('ashTitle').value=data.title;$('ashExcerpt').value=data.excerpt;$('ashBody').value=data.body}else{$('coopTitle').value=data.title;$('coopExcerpt').value=data.excerpt;$('coopBody').value=data.body}}}
async function loadNews(){const {data,error}=await supabase.from('news').select('*').order('created_at',{ascending:false});if(error){status($('adminStatus'),error.message,'error');return}currentNews=data||[];$('newsAdminList').innerHTML=currentNews.map(n=>`<div class="news-admin-item"><div><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.date)} — ${escapeHtml(n.excerpt)}</p>${(n.images||[]).length?`<div class="thumbs">${n.images.slice(0,5).map(u=>`<img src="${u}" alt="">`).join('')}</div>`:''}</div><div class="admin-actions"><button class="admin-btn secondary" data-edit="${n.id}">ویرایش</button><button class="admin-btn danger" data-delete="${n.id}">حذف</button></div></div>`).join('')||'<p class="hint">هنوز خبری ثبت نشده است.</p>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function saveContent(slug){const prefix=slug==='ashayer'?'ash':'coop';const payload={title:$(prefix+'Title').value.trim(),excerpt:$(prefix+'Excerpt').value.trim(),body:$(prefix+'Body').value.trim(),updated_at:new Date().toISOString()};const {error}=await supabase.from('site_content').update(payload).eq('slug',slug);status($('adminStatus'),error?error.message:'متن با موفقیت ذخیره شد.',error?'error':'ok')}
async function uploadFiles(files){const urls=[];for(const file of files){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const path=`news/${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('site-media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const {data}=supabase.storage.from('site-media').getPublicUrl(path);urls.push(data.publicUrl)}return urls}
async function saveNews(){const id=$('newsId').value||null;const payload={title:$('newsTitle').value.trim(),date:$('newsDate').value.trim(),excerpt:$('newsExcerpt').value.trim(),body:$('newsBody').value.trim()};if(!payload.title||!payload.date||!payload.body){status($('adminStatus'),'عنوان، تاریخ و متن کامل خبر الزامی است.','error');return}try{let images=[];if(id){const old=currentNews.find(n=>String(n.id)===String(id));images=old?.images||[]}const files=[...$('newsImages').files];if(files.length)images=await uploadFiles(files);payload.images=images;let result;if(id)result=await supabase.from('news').update({...payload,updated_at:new Date().toISOString()}).eq('id',id);else result=await supabase.from('news').insert(payload);if(result.error)throw result.error;status($('adminStatus'),'خبر با موفقیت ذخیره شد.','ok');clearForm();await loadNews()}catch(e){status($('adminStatus'),e.message||'خطا در ذخیره خبر','error')}}
$('sendLogin').onclick=async()=>{if(!configured)return status($('loginStatus'),'config.js هنوز تنظیم نشده است.','error');const email=$('email').value.trim().toLowerCase();if(!ownerAllowed(email))return status($('loginStatus'),'این ایمیل اجازه ورود ندارد.','error');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});status($('loginStatus'),error?error.message:'لینک ورود به ایمیل ارسال شد. همان لینک را باز کن.',error?'error':'ok')};
$('logout').onclick=()=>supabase.auth.signOut();$('cancelNews').onclick=clearForm;$('saveNews').onclick=saveNews;$('newsImages').onchange=()=>{$('selectedFiles').innerHTML=[...$('newsImages').files].map(f=>`<span class="hint">${escapeHtml(f.name)}</span>`).join(' • ')};
document.querySelectorAll('[data-save-content]').forEach(b=>b.onclick=()=>saveContent(b.dataset.saveContent));$('newsAdminList').onclick=async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const n=currentNews.find(x=>String(x.id)===String(edit.dataset.edit));if(!n)return;$('newsId').value=n.id;$('newsTitle').value=n.title;$('newsDate').value=n.date;$('newsExcerpt').value=n.excerpt;$('newsBody').value=n.body;$('newsFormTitle').textContent='ویرایش خبر';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}if(del){if(!confirm('این خبر حذف شود؟'))return;const {error}=await supabase.from('news').delete().eq('id',del.dataset.delete);status($('adminStatus'),error?error.message:'خبر حذف شد.',error?'error':'ok');await loadNews()}};
init();
