const fallbackContent={
 ashayer:{title:'عشایر؛ سرمایه ملّی',excerpt:'جامعه عشایری ایران یکی از ارزشمندترین بخش‌های اجتماعی، فرهنگی و اقتصادی کشور است؛ جامعه‌ای که در تولید، حفظ میراث فرهنگی و ارتباط پایدار با سرزمین نقش مهمی دارد.',body:'جامعه عشایری ایران یکی از ارزشمندترین بخش‌های اجتماعی، فرهنگی و اقتصادی کشور است؛ جامعه‌ای که در طول تاریخ، پیوندی عمیق و ناگسستنی با سرزمین، طبیعت، تولید و فرهنگ ایرانی داشته و بخش مهمی از هویت تاریخی و اجتماعی ایران را شکل داده است. عشایر تنها یک شیوه زندگی یا یک جامعه کوچ‌رو نیستند، بلکه مجموعه‌ای از ظرفیت‌های انسانی، اقتصادی، فرهنگی و زیست‌محیطی را در خود جای داده‌اند که حفظ، تقویت و حمایت از آن‌ها، بخشی از صیانت از سرمایه‌های ملی کشور به شمار می‌رود.\n\nزندگی عشایری بر پایه ارتباط مستقیم و مستمر انسان با طبیعت و بهره‌برداری متعادل از منابع طبیعی شکل گرفته است. عشایر با شناخت دقیق از مراتع، منابع آب، شرایط اقلیمی و ظرفیت‌های محیطی مناطق مختلف، طی نسل‌های متمادی شیوه‌ای از زندگی را توسعه داده‌اند که در آن دامداری، تولید محصولات دامی، کشاورزی در مقیاس محدود و بهره‌گیری از منابع طبیعی در کنار یکدیگر قرار گرفته‌اند.\n\nیکی از مهم‌ترین نقش‌های جامعه عشایری، مشارکت در تولید محصولات دامی و تأمین بخشی از نیازهای غذایی کشور است. اهمیت عشایر تنها به حوزه اقتصادی محدود نمی‌شود و فرهنگ، موسیقی، پوشش، صنایع دستی، آداب و رسوم و دانش بومی آنان نیز بخشی از میراث فرهنگی زنده ایران است.\n\nحمایت از عشایر باید به گونه‌ای باشد که ضمن حفظ هویت فرهنگی و اجتماعی آنان، زمینه افزایش توان اقتصادی و ارتقای کیفیت زندگی نیز فراهم شود. ایجاد زیرساخت‌های مناسب، تأمین آب شرب، دسترسی به خدمات، تأمین نهاده‌های دامی، تسهیل دسترسی به بازار و توسعه تعاونی‌های عشایری از جمله اقداماتی هستند که می‌توانند در توانمندسازی جامعه عشایری نقش داشته باشند.\n\nعشایر سرمایه‌ای ارزشمند برای ایران هستند؛ سرمایه‌ای که در آن تولید، فرهنگ، تجربه، هویت، دانش بومی و ارتباط با سرزمین در کنار یکدیگر قرار گرفته است.'},
 cooperative:{title:'چگونگی تعاونی',excerpt:'تعاونی، سازوکاری برای مشارکت افراد دارای نیازها و اهداف مشترک است؛ تعاونی عشایری نیز با سازمان‌دهی ظرفیت اعضا، تأمین نیازها، ارائه خدمات و تقویت تولید و بازار به جامعه عشایری کمک می‌کند.',body:'تعاونی یکی از مهم‌ترین شیوه‌های سازمان‌دهی اقتصادی و اجتماعی بر پایه مشارکت افراد است. در ساختار تعاونی، اشخاصی که دارای نیازها، منافع یا اهداف مشترک هستند، با گردهم آمدن و مشارکت در سرمایه و تصمیم‌گیری، تلاش می‌کنند بخشی از نیازهای اقتصادی و اجتماعی خود را به صورت جمعی تأمین کنند.\n\nتعاونی عشایری نوعی تشکل اقتصادی و اجتماعی است که با هدف سامان‌دهی بخشی از فعالیت‌ها و نیازهای جامعه عشایری شکل می‌گیرد. شرایط زندگی عشایری، پراکندگی جغرافیایی، کوچ، وابستگی معیشت به دامداری و نیاز به نهاده‌ها و خدمات، ضرورت وجود ساختارهایی را افزایش می‌دهد که بتوانند این نیازها را منسجم‌تر پیگیری کنند.\n\nیکی از کارکردهای مهم تعاونی‌های عشایری کمک به تأمین نیازهای اعضا است. این نیازها می‌تواند متناسب با شرایط منطقه شامل نهاده‌های دامی، علوفه، آرد، سوخت، سیلندر گاز مایع و سایر کالاها و خدمات مورد نیاز باشد.\n\nتعاونی همچنین می‌تواند در زمینه عرضه محصولات تولیدی نقش‌آفرین باشد. هنگامی که تولیدکنندگان به صورت فردی وارد بازار می‌شوند، ممکن است قدرت چانه‌زنی محدودی داشته باشند؛ اما تعاونی می‌تواند بخشی از تولید اعضا را در ساختاری منسجم‌تر جمع‌آوری و برای عرضه آن برنامه‌ریزی کند.\n\nتعاونی موفق باید در مسیر توانمندسازی اعضا حرکت کند. آموزش، اطلاع‌رسانی، ایجاد ارتباط میان اعضا، شناخت بازار، شفافیت مالی و اداری و مشارکت اعضا در تصمیم‌گیری از عناصر مهم یک تعاونی پایدار هستند.\n\nتعاونی عشایری در بهترین شکل خود، پلی میان اعضای عشایری و فرصت‌های اقتصادی و خدماتی است؛ پلی که نیازها و ظرفیت‌های اعضا را شناسایی می‌کند و ارتباط آنان را با دستگاه‌های اجرایی، بازار، تأمین‌کنندگان کالا و سایر بخش‌های اقتصادی تسهیل می‌نماید.'}
};
let news=[
{date:'۱۴۰۳/۱۲/۲۹',title:'برگزاری مجمع عمومی عادی سالیانه شرکت',text:'جلسه مجمع عمومی عادی سالیانه شرکت تعاونی عشایری کوه نور دهدشت با حضور اکثریت اعضاء برگزار گردید.',body:'جلسه مجمع عمومی عادی سالیانه سال مالی منتهی به 1403/12/29 شرکت تعاونی عشایری کوه نور دهدشت با حضور اکثریت اعضاء برگزار گردید. در این جلسه صورتهای مالی سال 1403 به تصویب اعضاء مجمع رسید.',images:['https://s6.uupload.ir/files/img_20260812_214231_921_rebj.jpg','https://s6.uupload.ir/files/img_20260812_214235_290_uw11.jpg','https://s6.uupload.ir/files/img_20260812_214236_565_7pnm.jpg','https://s6.uupload.ir/files/img_20260812_214240_309_d7re.jpg','https://s6.uupload.ir/files/img_20260812_214243_421_m4nm.jpg','https://s6.uupload.ir/files/img_20260812_214249_165_wdkv.jpg']},
{date:'۱۴۰۴',title:'تداوم خدمات آبرسانی و پشتیبانی از عشایر شهرستان کهگیلویه',text:'خدمات آبرسانی سیار و توزیع اقلام مورد نیاز عشایر شهرستان کهگیلویه به صورت مستمر انجام می‌شود.',body:'خدمات آبرسانی سیار با تانکر به عشایر شهرستان کهگیلویه توسط شرکت تعاونی عشایری کوه نور دهدشت به صورت مستمر صورت می پذیرد. آقای پروره مدیرعامل تعاونی عشایری کوه نور دهدشت در همین راستا بیان کردند که طی سال 1404 قریب به 1500 سرویس 12000 لیتری آب شرب با تانکر سیار تحویل عشایر شهرستان کهگیلویه گردیده است. وی افزود سال 1404 خدماتی اعم از توزیع آرد، علوفه دامی، توزیع نفت سفید، توزیع سیلندر گاز مایع و...... به صورت مستمر در اختیار عشایر تحت پوشش و سهامدار شرکت تعاونی قرار گرفته است.',images:['https://s6.uupload.ir/files/img_20260812_215010_415_84rr.jpg','https://s6.uupload.ir/files/img_20260812_215006_572_bmkq.jpg','https://s6.uupload.ir/files/img_20260812_215004_101_yomi.jpg','https://s6.uupload.ir/files/img_20260812_215000_262_fr6a.jpg','https://s6.uupload.ir/files/img_20260812_214958_234_7hze.jpg','https://s6.uupload.ir/files/img_20260812_214956_145_e3p3.jpg','https://s6.uupload.ir/files/img_20260812_214954_885_neu7.jpg']}
];
const docs=[{title:'استعلام شناسه ملی',url:'https://s6.uupload.ir/files/picsart_26-08-12_20-52-02-273_symw.png'},{title:'ثبت شرکت در دهدشت',url:'https://s6.uupload.ir/files/picsart_26-08-12_20-52-39-057_vja0.png'},{title:'آگهی تأسیس',url:'https://s6.uupload.ir/files/picsart_26-08-12_20-53-10-531_krf2.png'}];
const track=document.getElementById('newsTrack'),dots=document.getElementById('newsDots'),allNews=document.getElementById('allNewsList'),articleContent=document.getElementById('articleContent'),viewer=document.getElementById('documentViewer');let activeNews=0,timer;let content={...fallbackContent};
const cfg=window.SITE_CONFIG||{};const supabaseReady=!!(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase&&typeof window.supabase.createClient==='function');const sb=supabaseReady?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderNews(){track.innerHTML=news.map((n,i)=>`<article class="news-card" data-index="${i}"><div class="news-cover">${n.images?.[0]?`<img src="${n.images[0]}" alt="${esc(n.title)}" loading="lazy" onerror="this.parentElement.classList.add('image-failed');this.remove()">`:'<span aria-hidden="true">✦</span>'}</div><div class="news-body"><time class="news-date">${esc(n.date)}</time><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></div></article>`).join('');dots.innerHTML=news.map((_,i)=>`<button aria-label="نمایش خبر ${i+1}" data-dot="${i}" class="${i===0?'active':''}"></button>`).join('');allNews.innerHTML=news.map((n,i)=>`<button class="all-news-item" data-index="${i}"><div><time>${esc(n.date)}</time><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p></div><span aria-hidden="true">←</span></button>`).join('')}
function openModal(id){const m=document.getElementById(id);m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(id){const m=document.getElementById(id);m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function showArticle(i){const n=news[i];const gallery=n.images?.length?`<div class="article-gallery">${n.images.map((src,j)=>`<img src="${src}" alt="${esc(n.title)} - تصویر ${j+1}" loading="lazy">`).join('')}</div>`:'';articleContent.innerHTML=`<span class="eyebrow">خبر شرکت تعاونی</span><h2>${esc(n.title)}</h2><div class="article-meta">تاریخ انتشار: ${esc(n.date)}</div>${gallery}<p>${esc(n.body)}</p>`;openModal('articleModal')}
function showContent(slug){const c=content[slug];document.getElementById('contentModalBody').innerHTML=`<div class="content-modal-body"><span class="eyebrow">معرفی</span><h2>${esc(c.title)}</h2><div class="article-meta">متن کامل</div><p>${esc(c.body)}</p></div>`;openModal('contentModal')}
function setActiveDot(i){activeNews=i;dots.querySelectorAll('button').forEach((b,j)=>b.classList.toggle('active',j===i))}function goToNews(i){i=(i+news.length)%news.length;const card=track.querySelector(`[data-index="${i}"]`);if(!card)return;activeNews=i;track.scrollTo({left:card.offsetLeft-(track.clientWidth-card.offsetWidth)/2,behavior:'smooth'});setActiveDot(i)}function restartTimer(){clearInterval(timer);timer=setInterval(()=>goToNews(activeNews+1),5000)}
async function loadRemote(){if(!sb)return;try{const cr=await sb.from('site_content').select('*').in('slug',['ashayer','cooperative']);if(!cr.error)cr.data.forEach(x=>{content[x.slug]=x});document.getElementById('ashayerExcerpt').textContent=content.ashayer.excerpt;document.getElementById('cooperativeExcerpt').textContent=content.cooperative.excerpt;const nr=await sb.from('news').select('*').order('created_at',{ascending:false});if(!nr.error&&nr.data?.length){news=nr.data.map(n=>({...n,images:Array.isArray(n.images)?n.images:[]}));renderNews();goToNews(0);restartTimer()}}catch(e){console.warn('Remote content unavailable',e)}}
renderNews();document.getElementById('ashayerExcerpt').textContent=content.ashayer.excerpt;document.getElementById('cooperativeExcerpt').textContent=content.cooperative.excerpt;
document.querySelectorAll('.menu-card').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'}));document.querySelectorAll('.read-more').forEach(b=>b.onclick=()=>showContent(b.dataset.content));document.getElementById('openNews').onclick=()=>openModal('newsModal');document.getElementById('nextNews').onclick=()=>{goToNews(activeNews+1);restartTimer()};document.getElementById('prevNews').onclick=()=>{goToNews(activeNews-1);restartTimer()};dots.onclick=e=>{if(e.target.dataset.dot!==undefined){goToNews(Number(e.target.dataset.dot));restartTimer()}};track.onclick=e=>{const c=e.target.closest('.news-card');if(c)showArticle(Number(c.dataset.index))};allNews.onclick=e=>{const c=e.target.closest('.all-news-item');if(c)showArticle(Number(c.dataset.index))};document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close)});document.addEventListener('keydown',e=>{if(e.key==='Escape'){['newsModal','articleModal','contentModal'].forEach(closeModal)}if(e.key==='ArrowLeft')goToNews(activeNews+1);if(e.key==='ArrowRight')goToNews(activeNews-1)});track.addEventListener('pointerdown',()=>clearInterval(timer));track.addEventListener('pointerup',restartTimer);track.addEventListener('touchend',restartTimer,{passive:true});
track.addEventListener('scroll',()=>{const cards=[...track.querySelectorAll('.news-card')];if(!cards.length)return;const center=track.scrollLeft+track.clientWidth/2;let best=0,dist=Infinity;cards.forEach((c,i)=>{const d=Math.abs(c.offsetLeft+c.offsetWidth/2-center);if(d<dist){dist=d;best=i}});setActiveDot(best)},{passive:true});
function renderDoc(i=0){const d=docs[i];viewer.innerHTML=`<img src="${d.url}" alt="${esc(d.title)}" loading="lazy"><div class="document-caption"><strong>${esc(d.title)}</strong><br>تصویر سند رسمی ارائه‌شده در بخش اسناد و مدارک.</div>`;document.querySelectorAll('.document-tab').forEach((b,j)=>b.classList.toggle('active',j===i))}document.querySelectorAll('.document-tab').forEach(b=>b.onclick=()=>renderDoc(Number(b.dataset.doc)));renderDoc();restartTimer();loadRemote();

function renderIranDate(){
    const el=document.getElementById('iranDate');
    if(!el)return;
    try{
        const date=new Intl.DateTimeFormat(
            'fa-IR-u-ca-persian',
            {
                timeZone:'Asia/Tehran',
                day:'numeric',
                month:'long',
                year:'numeric'
            }
        ).format(new Date());
        el.textContent='امروز '+date;
    }catch(e){
        el.textContent='امروز';
    }
}
renderIranDate();
setInterval(renderIranDate,60000);
